https://link.springer.com/article/10.1186/s12859-016-1442-6

Gapmaps etc

https://www.researchgate.net/profile/Corinna-Vehlow/publication/280878061_The_State_of_the_Art_in_Visualizing_Group_Structures_in_Graphs/links/55c9d3e608aea2d9bdc9c167/The-State-of-the-Art-in-Visualizing-Group-Structures-in-Graphs.pdf

State of the art in group structure (2015)

https://www.nature.com/articles/nmeth.1902
Heat maps (2012)

https://cloud.genepattern.org/gp/pages/protocols/ClassDiscovery.html


Functional annotation
https://david.ncifcrf.gov/

CACNB2
SPARCL1
HIF3A
TIMP4
ZBTB16
FAM107A


* Signals

Tried to make some signals with controllers, but mostly they didn't propagate enough and I didn't figure it out


* Alt layout

Having the labels and tree on the same side (as in https://youtu.be/4_AJxrxPYlk?si=cEaKx8JG_j8-uPsp&t=4915) would be cool, but hard.

Maybe if you use marks instead of Axes for labels? Ugh

This actually works kind of, but it has the same problem as axes. You'd have to do the labels on the tree, not the hm
        {:type "text"
         :from {:data "htree-leaf"}
         :encode {:enter {:y {:field "y"}
                          :x0 {:value 0}
                          :align {:value :right}
                          :text {:field "id"}}}}



https://tvpham.github.io/ion/heatmap.html


OOH, select and zoom, I can see a lot of uses for that...


OOh, seriation, I need that
https://cran.r-project.org/web/packages/heatmaply/vignettes/heatmaply.html#normalize

Sudden realizations about vega:
- they tree layout seems to control tree branch order, not the data (changing the data does not changee the display). But I couldn't quite figure out where it does that.   oh its from d3. https://github.com/d3/d3-hierarchy/blob/main/src/hierarchy/index.js


Whoa
http://www.heatmapper.ca/

Newer version (Python and webassembly)
https://wishartlab.github.io/heatmapper2/
