* Heroku 

Demo site:
https://shrouded-escarpment-03060-744eda4cc53f.herokuapp.com/
https://git.heroku.com/shrouded-escarpment-03060.git

* See also

https://kit-clj.github.io/ (general web framework, addresses rather different issues)

* Bootstrap is old-fashioned

[What UI frameworks do y'all use or recommend : r/reactjs](https://www.reddit.com/r/reactjs/comments/1d2ptx2/what_ui_frameworks_do_yall_use_or_recommend/)

* Feed theory

Right now, params are organized by feed, so if a parameter is used for two feeds you need to set it twice, which is ugh.

Better: some declarative method to say which params are used for a feed.

Also, the whole model breaks down if you want to replicate views. Like, two stock ticker graphs with different settings!

[:div (stock-ticker "IBM") (stock-ticker "APPL:")]

** Followup

Redid feeds, but parameters are still iffy
Feeds, Parameters, and Forms – need to be reconciled somehow

* Add stuff!

Some of this is for advertising/showing off, some for campAIgn

** DONE Violin plot
** Blocky/Vaguely
** OAuth
** DB backend
** ORMish functionality (maybe)
** Re-frame rationalization and cleanup
** Ag-grid actually componentized properly
** Build out forms/ops
** DONE Blocktype OH YEAH just fold in that thing I did
** Navigation!


WTF????
https://web.archive.org/web/20190608203722/http://reagent-project.github.io/docs/master/ReactFeatures.html
https://github.com/reagent-project/reagent/blob/master/doc/ReactFeatures.md#hooks


* Nav notes

Why are BIDI/Pushy so horrible? Why is there not a standard solution

Want tabs widget to automatically generate subroutes of whatever the current route is. Seems simple and obvious, but not sure how to do it

Should include hierarchical nav header, as option at least. 
